### ISSUE TITLE
Problems installing

### ISSUE THREAD

**Issue by retog** [nikku/wuffle#32]
Hi, I've installed the docker image and I can see a board with the configured columns but I have the following issues/questions:
- as title it shows the first repo in the array of repositories (in the format `nikku/wuffle`)
- all columns are empty, even though I have an issue with the label "ready" (I've configured the columns as in the example config)
- when clicking on the top-right icon which should allow to log-in with GitHub I'm being eventually redirected to http://localhost:3000/board even though "localhost" never appears in the application configuration on GitHub
![image](https://user-images.githubusercontent.com/110756/61182908-49eb9280-a63a-11e9-9163-2285e403cb98.png)
- When configuring the environment variables I wasn't sue about the SESSION_SECRET, I then assumed I could enter an arbitrary String.

**Comment by nikku** [comment]
The preferred way of setting up the application is via a local development setup. The docker images are meant for production use only.

Did you configure your app providing [all required environment variables](https://github.com/nikku/wuffle/blob/master/docs/CONFIG.md)?

**Comment by retog** [comment]
Thank @nikku,I forgot the BASE_URL variable, after adding I'm no longer redirected to localhost. However I still se no card on the board.

**Comment by nikku** [comment]
Which exact steps did you undertake? How did you configure the board?

**Comment by joannenolan-sky** [comment]
This could be because you have not updated your `User authorization callback URL` on the app setting page(`https://github.com/settings/apps/<app-name>`). It should be `<BASE_URL>/wuffle/login/callback`. It is probably still set to `http://localhost:3000/wuffle/login/callback` which it is set to as a default.

**Comment by nikku** [comment]
The setup instructions are not great. Bear with me, as I think about how to improve it.

:grimacing:

**Comment by retog** [comment]
What I've basically done is adding and fixing env-variables till I no longer got an error message....

I ended up with the following configuration in docker-compose (the first part is traefik sepcific which I use for SSL termination):
```
wuffle:
    image: nrehwaldt/wuffle
    labels:
      traefik.frontend.rule: Host:wuffle.factsmission.org
      traefik.frontend.entryPoints: https
      traefik.port: '3000'
      traefik.enable: 'true'
    volumes:
      - ./wuffle/wuffle.config.js:/app/packages/app/wuffle.config.js # this didn't work, so I added config as variable below
    environment:
      APP_ID: 35560 
      GITHUB_CLIENT_ID: Iv1.026bc702254c070f
      GITHUB_CLIENT_SECRET: *****
      WEBHOOK_SECRET: sameAsEnteredIn AppConfig
      PRIVATE_KEY: LS0tL......WS0tLS0tCg==
      SESSION_SECRET: justWroteSomething
      BASE_URL: https://wuffle.factsmission.org/board
      BOARD_CONFIG: '{"columns":[{"name":"Inbox","label":null},{"name":"Backlog","label":"backlog"},{"name":"Ready","label":"ready"},{"name":"In Progress","label":"in progress"},{"name":"Needs Review","label":"needs review"},{"name":"Done","label":null,"closed":true}],"repositories":["retog/repo1", "org/repo2"]}'
    restart: unless-stopped
```
This is some of the config in GitHub:

![image](https://user-images.githubusercontent.com/110756/61205823-5ed72d00-a6f1-11e9-83f3-daf6a419bebd.png)
